# # This is a basic workflow to help you get started with Actions

# name: AUTO DEPLOYMENT

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@master

#       - name: EXTRACT NPM VERSION
#         id: extract_version
#         uses: Saionaro/extract-package-version@v1.0.6
#       -
#         name: SETUP QEMUX
#         uses: docker/setup-qemu-action@v1
#       -
#         name: SET UP DOCKERX
#         uses: docker/setup-buildx-action@v1
#       -
#         name: LOGIN TO DOCKERHUB
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#       -
#         name: Build Docker and Push to TICKET_EXCHANGE_BACK
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           file: ./Dockerfile
#           tags: |
#             teamcaramella/ticket_exchange_back:latest
#             teamcaramella/ticket_exchange_back:v${{ steps.extract_version.outputs.version }}
#       - 
#         name: MAKE RELEASE DATE
#         id: date
#         run: echo "release_time=$(TZ=Asia/Seoul date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
#       - 
#         name: CREATE RELEASE
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: v${{ steps.extract_version.outputs.version }}
#           release_name: Release v${{ steps.extract_version.outputs.version }} [${{ env.release_time }}]
#           body: AUTO RELEASE MADE FROM workflows
#           draft: true
